---
openapi: 3.0.0
info:
  title: "Test Api"
  description: "learn some things"
  version: "0.0.1"
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: users
    description: things about users

