---
openapi: 3.0.0
info:
  title: "Duenna Api"
  description: "learn some things"
  version: "0.0.1"
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: generic
    description: overall things
  - name: users
    description: things about users

